services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      - POSTGRES_DB=${DB_NAME:-my-bingo-db}
      - POSTGRES_USER=${DB_USER:-my-user-bingo-db}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-my-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_bingo:/var/lib/postgresql/data

volumes:
  postgres_bingo: