# Generated by Django 5.1.3 on 2024-12-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingoAPI', '0002_alter_player_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingocard',
            name='numbers',
            field=models.JSONField(),
        ),
    ]
